all:
  children:
    winvm:
      hosts:
        WINDOWS10:
          ansible_host: 192.168.56.10
          vagrant_box: gusztavvargadr/visual-studio
      vars:
        ansible_user: vagrant
        ansible_password: vargrant
        ansible_connection: winrm
        ansible_port: 5985
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore

        vagrant_ports:
          rdp:
            guest: 3389
            host: 29500
          ssh:
            guest: 22
            host: 29600
          winrm_http:
            guest: 5985
            host: 29700
          winrm_https:
            guest: 5986
            host: 29800
          smb:
            guest: 445
            host: 29900
