---
- name: Install packages
  win_chocolatey:
    name: "{{ lookup('community.general.flattened', base_packages) }}"
    state: present
  tags:
    - packages

- name: install Win32-OpenSSH service
  win_chocolatey:
    name: openssh
    package_params: /SSHServerFeature
    state: present
  tags:
    - packages

- name: set the default shell to PowerShell
  win_regedit:
    path: HKLM:\SOFTWARE\OpenSSH
    name: DefaultShell
    data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    type: string
    state: present
